from download import prices

## OMX 30
prices('ABB.ST')
prices('ALFA.ST')
prices('ASSA-B.ST')
prices('AZN.ST')
prices('ATCO-A.ST')
prices('ATCO-B.ST')
prices('BOL.ST')
prices('ELUX-B.ST')
prices('ERIC-B.ST')
prices('GETI-B.ST')
prices('HMB.ST')
prices('INVE-B.ST')
prices('LUPE.ST')
prices('MTG-B.ST')
prices('NOKI-SEK.ST')
prices('NDA-SEK.ST')
prices('SAND.ST')
prices('SCA-B.ST')
prices('SCV-B.ST')
prices('SEB-A.ST')
prices('SECU-B.ST')
prices('SKA-B.ST')
prices('SKF-B.ST')
prices('SSAB-A.ST')
prices('SHB-A.ST')
prices('SWED-A.ST')
prices('SWMA.ST')
prices('TEL2-B.ST')
prices('TLSN.ST')
prices('VOLV-B.ST')
